### ISSUE TITLE
Mapping & Counting page

### ISSUE THREAD

**Issue by AgentKumara** [GenomicsAotearoa/RNA-seq-workshop#20]
Samtools section: 
- Minor inconsistency where the explanation of arguments for Samtools (view and sort) is not present.
- samtools view -S flag "Ignored for compatibility with previous samtools versions. Previously this option was required if input was in SAM format, but now the correct format is automatically detected by examining the first few characters of input." [samtools 10.10 manual](http://www.htslib.org/doc/1.10/samtools-view.html) - does this mean we don't need it anymore?
- samtools sort description repeated (above and below code block)

MultiQC section:
- In the MultiQC section at the bottom, there is a note on MultiQC  reports labelled as Bowtie2. Maybe you could mention the usage of MultiQC config yaml?

Subread and FeatureCounts section:
- ```module load Subread``` needs the software version number

**Comment by DininduSenanayake** [comment]
* `module load Subread` needs the software version number ✔️ 
* samtools sort description repeated (above and below code block) ✔️  
* WIth regards to `sammtools view -S`, let's leave it as it is for moment but I have added a note saying that is not needed for newer versions and why ✔️ 
* Minor inconsistency where the explanation of arguments for Samtools (view and sort) is not present. ✔️
 
>In the MultiQC section at the bottom, there is a note on MultiQC reports labelled as Bowtie2. Maybe you could mention the usage of MultiQC config yaml?

We will add a note to it on the main section with the hope of adding more content to supplementary OR add a short section on it to https://genomicsaotearoa.github.io/Workshop-Bash_Scripting_And_HPC_Job_Scheduler/ workshop material
